//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class УчебнаяEntities : DbContext
    {
        private static УчебнаяEntities _context;

        public static УчебнаяEntities GetContext()
        {
            if (_context == null)
                _context = new УчебнаяEntities();
            return _context;
        }
        public УчебнаяEntities()
            : base("name=УчебнаяEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Предприятия> Предприятия { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
    }
}
