//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сельскохозяйственные_работы
    {
        public int ID_предприятия { get; set; }
        public Nullable<int> Название_предприятия { get; set; }
        public string наименование_товара { get; set; }
        public string единица_измерения { get; set; }
        public Nullable<decimal> цена { get; set; }
        public Nullable<System.DateTime> Дата_доставки { get; set; }
        public Nullable<decimal> Объём { get; set; }
        public Nullable<decimal> Себестоимость { get; set; }
    }
}
